import type { BatteryProduct, Inverter, MountingStructure, PvModule } from "./types";

/**
 * BIBLIOTHÈQUE D'ÉQUIPEMENTS — DONNÉES DE DÉMONSTRATION.
 *
 * Les caractéristiques ci-dessous sont des valeurs génériques et fictives,
 * destinées uniquement à faire fonctionner le moteur de calcul. Elles ne
 * correspondent à aucune fiche technique constructeur réelle.
 * Remplacer par des données de fiches techniques avant tout usage d'ingénierie.
 */

export const DEMO_DATA_NOTICE =
  "DONNÉES DE DÉMONSTRATION — caractéristiques génériques, non issues de fiches techniques constructeur.";

export const DEMO_MODULES: PvModule[] = [
  {
    id: "mod-demo-400-perc",
    manufacturer: "Générique (démo)",
    model: "DEMO-PERC-400",
    technology: "Mono PERC P-type",
    pmaxW: 400,
    vocV: 45.5,
    vmpV: 37.8,
    iscA: 11.2,
    impA: 10.6,
    tempCoefVocPctC: -0.28,
    tempCoefPmaxPctC: -0.35,
    lengthMm: 1755,
    widthMm: 1038,
    efficiencyPct: 20.5,
    stc: "1000 W/m², 25 °C, AM1.5",
    demo: true,
  },
  {
    id: "mod-demo-500-topcon",
    manufacturer: "Générique (démo)",
    model: "DEMO-TOPCon-500",
    technology: "N-type TOPCon",
    pmaxW: 500,
    vocV: 46.2,
    vmpV: 38.9,
    iscA: 13.7,
    impA: 12.9,
    tempCoefVocPctC: -0.25,
    tempCoefPmaxPctC: -0.3,
    lengthMm: 1960,
    widthMm: 1134,
    efficiencyPct: 22.5,
    stc: "1000 W/m², 25 °C, AM1.5",
    demo: true,
  },
  {
    id: "mod-demo-580-topcon",
    manufacturer: "Générique (démo)",
    model: "DEMO-TOPCon-580",
    technology: "N-type TOPCon",
    pmaxW: 580,
    vocV: 52.1,
    vmpV: 43.6,
    iscA: 14.1,
    impA: 13.3,
    tempCoefVocPctC: -0.25,
    tempCoefPmaxPctC: -0.29,
    lengthMm: 2278,
    widthMm: 1134,
    efficiencyPct: 22.4,
    stc: "1000 W/m², 25 °C, AM1.5",
    demo: true,
  },
  {
    id: "mod-demo-450-hjt",
    manufacturer: "Générique (démo)",
    model: "DEMO-HJT-450",
    technology: "HJT",
    pmaxW: 450,
    vocV: 48.6,
    vmpV: 40.9,
    iscA: 11.6,
    impA: 11.0,
    tempCoefVocPctC: -0.22,
    tempCoefPmaxPctC: -0.24,
    lengthMm: 1860,
    widthMm: 1134,
    efficiencyPct: 21.3,
    stc: "1000 W/m², 25 °C, AM1.5",
    demo: true,
  },
  {
    id: "mod-demo-440-abc",
    manufacturer: "Générique (démo)",
    model: "DEMO-ABC-440",
    technology: "Back-contact / ABC",
    pmaxW: 440,
    vocV: 47.3,
    vmpV: 39.4,
    iscA: 11.8,
    impA: 11.2,
    tempCoefVocPctC: -0.23,
    tempCoefPmaxPctC: -0.26,
    lengthMm: 1762,
    widthMm: 1134,
    efficiencyPct: 22.0,
    stc: "1000 W/m², 25 °C, AM1.5",
    demo: true,
  },
];

export const DEMO_INVERTERS: Inverter[] = [
  {
    id: "inv-demo-5k-1ph",
    manufacturer: "Générique (démo)",
    model: "DEMO-STRING-5K",
    acPowerKw: 5,
    maxDcPowerKw: 7.5,
    mpptVminV: 90,
    mpptVmaxV: 520,
    maxDcVoltageV: 600,
    maxInputCurrentA: 16,
    mpptCount: 2,
    maxStringsPerMppt: 1,
    efficiencyPct: 97.5,
    phases: 1,
    demo: true,
  },
  {
    id: "inv-demo-10k-3ph",
    manufacturer: "Générique (démo)",
    model: "DEMO-STRING-10K",
    acPowerKw: 10,
    maxDcPowerKw: 15,
    mpptVminV: 160,
    mpptVmaxV: 850,
    maxDcVoltageV: 1000,
    maxInputCurrentA: 16,
    mpptCount: 2,
    maxStringsPerMppt: 2,
    efficiencyPct: 98.2,
    phases: 3,
    demo: true,
  },
  {
    id: "inv-demo-25k-3ph",
    manufacturer: "Générique (démo)",
    model: "DEMO-STRING-25K",
    acPowerKw: 25,
    maxDcPowerKw: 37.5,
    mpptVminV: 200,
    mpptVmaxV: 850,
    maxDcVoltageV: 1100,
    maxInputCurrentA: 26,
    mpptCount: 3,
    maxStringsPerMppt: 2,
    efficiencyPct: 98.5,
    phases: 3,
    demo: true,
  },
  {
    id: "inv-demo-100k-3ph",
    manufacturer: "Générique (démo)",
    model: "DEMO-STRING-100K",
    acPowerKw: 100,
    maxDcPowerKw: 150,
    mpptVminV: 200,
    mpptVmaxV: 1000,
    maxDcVoltageV: 1100,
    maxInputCurrentA: 30,
    mpptCount: 8,
    maxStringsPerMppt: 2,
    efficiencyPct: 98.8,
    phases: 3,
    demo: true,
  },
];

export const DEMO_BATTERIES: BatteryProduct[] = [
  {
    id: "bat-demo-5",
    manufacturer: "Générique (démo)",
    model: "DEMO-LFP-5",
    nominalKwh: 5,
    dodPct: 90,
    roundTripPct: 92,
    maxChargeKw: 2.5,
    maxDischargeKw: 2.5,
    cycleLife: 6000,
    demo: true,
  },
  {
    id: "bat-demo-10",
    manufacturer: "Générique (démo)",
    model: "DEMO-LFP-10",
    nominalKwh: 10,
    dodPct: 90,
    roundTripPct: 92,
    maxChargeKw: 5,
    maxDischargeKw: 5,
    cycleLife: 6000,
    demo: true,
  },
  {
    id: "bat-demo-30",
    manufacturer: "Générique (démo)",
    model: "DEMO-LFP-30",
    nominalKwh: 30,
    dodPct: 90,
    roundTripPct: 94,
    maxChargeKw: 15,
    maxDischargeKw: 15,
    cycleLife: 6000,
    demo: true,
  },
];

export const DEMO_STRUCTURES: MountingStructure[] = [
  {
    id: "str-demo-toit-tuile",
    manufacturer: "Générique (démo)",
    model: "DEMO-RAIL-TUILE",
    type: "Toiture inclinée — crochets",
    material: "Aluminium / inox",
    maxTiltDeg: 45,
    demo: true,
  },
  {
    id: "str-demo-lest",
    manufacturer: "Générique (démo)",
    model: "DEMO-LEST-15",
    type: "Toiture-terrasse — lestée",
    material: "Aluminium",
    maxTiltDeg: 15,
    demo: true,
  },
  {
    id: "str-demo-sol",
    manufacturer: "Générique (démo)",
    model: "DEMO-SOL-25",
    type: "Au sol — pieux battus",
    material: "Acier galvanisé",
    maxTiltDeg: 30,
    demo: true,
  },
];

export const getModule = (id: string): PvModule =>
  DEMO_MODULES.find((m) => m.id === id) ?? DEMO_MODULES[0]!;

export const getInverter = (id: string): Inverter =>
  DEMO_INVERTERS.find((i) => i.id === id) ?? DEMO_INVERTERS[0]!;
