/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as CalepinageRouteImport } from './routes/calepinage'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EquipementsRouteImport } from './routes/equipements'
import { Route as EtudeRouteImport } from './routes/etude'
import { Route as MethodologieRouteImport } from './routes/methodologie'
import { Route as ProjetsRouteImport } from './routes/projets'
import { Route as RapportRouteImport } from './routes/rapport'
import { Route as ResultatsRouteImport } from './routes/resultats'
import { Route as UnifilaireRouteImport } from './routes/unifilaire'
import { Route as ApiDesignReviewRouteImport } from './routes/api/design-review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const CalepinageRoute = CalepinageRouteImport.update({
  id: '/calepinage',
  path: '/calepinage',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipementsRoute = EquipementsRouteImport.update({
  id: '/equipements',
  path: '/equipements',
  getParentRoute: () => rootRouteImport,
} as any)
const EtudeRoute = EtudeRouteImport.update({
  id: '/etude',
  path: '/etude',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologieRoute = MethodologieRouteImport.update({
  id: '/methodologie',
  path: '/methodologie',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsRoute = ProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportRoute = RapportRouteImport.update({
  id: '/rapport',
  path: '/rapport',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultatsRoute = ResultatsRouteImport.update({
  id: '/resultats',
  path: '/resultats',
  getParentRoute: () => rootRouteImport,
} as any)
const UnifilaireRoute = UnifilaireRouteImport.update({
  id: '/unifilaire',
  path: '/unifilaire',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDesignReviewRoute = ApiDesignReviewRouteImport.update({
  id: '/api/design-review',
  path: '/api/design-review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/calepinage': typeof CalepinageRoute
  '/contact': typeof ContactRoute
  '/equipements': typeof EquipementsRoute
  '/etude': typeof EtudeRoute
  '/methodologie': typeof MethodologieRoute
  '/projets': typeof ProjetsRoute
  '/rapport': typeof RapportRoute
  '/resultats': typeof ResultatsRoute
  '/unifilaire': typeof UnifilaireRoute
  '/api/design-review': typeof ApiDesignReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/calepinage': typeof CalepinageRoute
  '/contact': typeof ContactRoute
  '/equipements': typeof EquipementsRoute
  '/etude': typeof EtudeRoute
  '/methodologie': typeof MethodologieRoute
  '/projets': typeof ProjetsRoute
  '/rapport': typeof RapportRoute
  '/resultats': typeof ResultatsRoute
  '/unifilaire': typeof UnifilaireRoute
  '/api/design-review': typeof ApiDesignReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/calepinage': typeof CalepinageRoute
  '/contact': typeof ContactRoute
  '/equipements': typeof EquipementsRoute
  '/etude': typeof EtudeRoute
  '/methodologie': typeof MethodologieRoute
  '/projets': typeof ProjetsRoute
  '/rapport': typeof RapportRoute
  '/resultats': typeof ResultatsRoute
  '/unifilaire': typeof UnifilaireRoute
  '/api/design-review': typeof ApiDesignReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/calepinage'
    | '/contact'
    | '/equipements'
    | '/etude'
    | '/methodologie'
    | '/projets'
    | '/rapport'
    | '/resultats'
    | '/unifilaire'
    | '/api/design-review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/calepinage'
    | '/contact'
    | '/equipements'
    | '/etude'
    | '/methodologie'
    | '/projets'
    | '/rapport'
    | '/resultats'
    | '/unifilaire'
    | '/api/design-review'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/calepinage'
    | '/contact'
    | '/equipements'
    | '/etude'
    | '/methodologie'
    | '/projets'
    | '/rapport'
    | '/resultats'
    | '/unifilaire'
    | '/api/design-review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  CalepinageRoute: typeof CalepinageRoute
  ContactRoute: typeof ContactRoute
  EquipementsRoute: typeof EquipementsRoute
  EtudeRoute: typeof EtudeRoute
  MethodologieRoute: typeof MethodologieRoute
  ProjetsRoute: typeof ProjetsRoute
  RapportRoute: typeof RapportRoute
  ResultatsRoute: typeof ResultatsRoute
  UnifilaireRoute: typeof UnifilaireRoute
  ApiDesignReviewRoute: typeof ApiDesignReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calepinage': {
      id: '/calepinage'
      path: '/calepinage'
      fullPath: '/calepinage'
      preLoaderRoute: typeof CalepinageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipements': {
      id: '/equipements'
      path: '/equipements'
      fullPath: '/equipements'
      preLoaderRoute: typeof EquipementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etude': {
      id: '/etude'
      path: '/etude'
      fullPath: '/etude'
      preLoaderRoute: typeof EtudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodologie': {
      id: '/methodologie'
      path: '/methodologie'
      fullPath: '/methodologie'
      preLoaderRoute: typeof MethodologieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets': {
      id: '/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof ProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapport': {
      id: '/rapport'
      path: '/rapport'
      fullPath: '/rapport'
      preLoaderRoute: typeof RapportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultats': {
      id: '/resultats'
      path: '/resultats'
      fullPath: '/resultats'
      preLoaderRoute: typeof ResultatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unifilaire': {
      id: '/unifilaire'
      path: '/unifilaire'
      fullPath: '/unifilaire'
      preLoaderRoute: typeof UnifilaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/design-review': {
      id: '/api/design-review'
      path: '/api/design-review'
      fullPath: '/api/design-review'
      preLoaderRoute: typeof ApiDesignReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  CalepinageRoute: CalepinageRoute,
  ContactRoute: ContactRoute,
  EquipementsRoute: EquipementsRoute,
  EtudeRoute: EtudeRoute,
  MethodologieRoute: MethodologieRoute,
  ProjetsRoute: ProjetsRoute,
  RapportRoute: RapportRoute,
  ResultatsRoute: ResultatsRoute,
  UnifilaireRoute: UnifilaireRoute,
  ApiDesignReviewRoute: ApiDesignReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
